### ISSUE TITLE
Consider making `PublicNamespace` a user-defined variable instead of a constant

### ISSUE THREAD

**Issue by RamXX** [openvex/go-vex#19]
Currently, `PublicNamespace` is defined [as a constant](https://github.com/openvex/go-vex/blob/main/pkg/vex/vex.go#L43), but if I understand its purpose correctly, "@id" is a direct URL to the document, so it is conceivable that a software vendor may want to setup their own server to provide those documents. Thanks!

**Comment by puerco** [comment]
Hey @RamXX   I kept forgetting to address this issue every time. Sorry about that!

I filed #46 which should make the namespace configurable.
